// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------
using CodeOfChaos.Ansi.Generators.Xml;
using CodeOfChaos.GeneratorTools;
using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Xml.Serialization;

namespace CodeOfChaos.Ansi.Generators;
// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------
[Generator]
public class AnsiStringBuilderGenerator : IIncrementalGenerator {
    private static Regex FindFirstColorName { get; } = new(@"ASB\.[^\\\/]*\.xml");

    // -----------------------------------------------------------------------------------------------------------------
    // Methods
    // -----------------------------------------------------------------------------------------------------------------
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        IncrementalValueProvider<ImmutableArray<AdditionalText>> provider = context.AdditionalTextsProvider
            .Where(IsColorFile)
            .Collect();

        context.RegisterSourceOutput(provider, GenerateCode);
    }

    private static bool IsColorFile(AdditionalText f) => FindFirstColorName.IsMatch(f.Path);

    private static void GenerateCode(SourceProductionContext context, ImmutableArray<AdditionalText> files) {
        IEnumerable<ColorEntry> colors = files.SelectMany(file => ParseColorFile(context, file)).ToArray();
        var builder = new GeneratorStringBuilder();

        #region AnsiColorStore
        context.AddSource("AnsiColorStore.g.cs", builder
            .AppendAutoGenerated()
            .AppendNamespace("CodeOfChaos.Ansi")
            .AppendLine("public class AnsiColorStore {")
            .ForEach(colors, itemFormatter: (stringBuilder, entry) => stringBuilder
                .AppendLineIndented($"public static readonly CodeOfChaos.Ansi.ByteVector3 {entry.Name} = new({entry.Colors});")
            )
            .AppendLine("}")
            .ToStringAndClear());
        #endregion

        #region Fore & Background
        foreach (string section in new[] { "Foreground", "Background", "Underline" }) {
            context.AddSource($"Ansi{section}Builder.g.cs", builder
                .AppendAutoGenerated()
                .AppendNamespace("CodeOfChaos.Ansi")
                .AppendLine($"public partial class Ansi{section}Builder {{")
                .ForEach(colors, itemFormatter: (stringBuilder, entry) => stringBuilder
                    .AppendBodyIndented($$"""
                        #region {{entry.Name}}
                        public string {{entry.Name}}(string text) => $"{CodeOfChaos.Ansi.AnsiCodes.Rgb{{section}}Color(CodeOfChaos.Ansi.AnsiColorStore.{{entry.Name}})}{text}{CodeOfChaos.Ansi.AnsiCodes.ResetGraphicsModes}";

                        public Ansi{{section}}Builder Append{{entry.Name}}(string text) => BuilderAction(() => {
                            Builder
                                .Append(CodeOfChaos.Ansi.AnsiCodes.Rgb{{section}}Color(CodeOfChaos.Ansi.AnsiColorStore.{{entry.Name}}))
                                .Append(text)
                                .Append(CodeOfChaos.Ansi.AnsiCodes.ResetGraphicsModes);
                        });

                        public Ansi{{section}}Builder Append{{entry.Name}}(Func<string> action) => BuilderAction(() => {
                            Builder
                                .Append(CodeOfChaos.Ansi.AnsiCodes.Rgb{{section}}Color(CodeOfChaos.Ansi.AnsiColorStore.{{entry.Name}}))
                                .Append(action())
                                .Append(CodeOfChaos.Ansi.AnsiCodes.ResetGraphicsModes);
                        });

                        public Ansi{{section}}Builder Append{{entry.Name}}(Action<Ansi{{section}}Builder> action) => BuilderAction(() => {
                            Builder.Append(CodeOfChaos.Ansi.AnsiCodes.Rgb{{section}}Color(CodeOfChaos.Ansi.AnsiColorStore.{{entry.Name}}));
                            action(this);
                            Builder.Append(CodeOfChaos.Ansi.AnsiCodes.ResetGraphicsModes);
                        });

                        public Ansi{{section}}Builder Append{{entry.Name}}Line(string text) => BuilderAction(() => {
                            Builder
                                .Append(CodeOfChaos.Ansi.AnsiCodes.Rgb{{section}}Color(CodeOfChaos.Ansi.AnsiColorStore.{{entry.Name}}))
                                .Append(text)
                                .AppendLine(CodeOfChaos.Ansi.AnsiCodes.ResetGraphicsModes);
                        });

                        public Ansi{{section}}Builder Append{{entry.Name}}Line(Func<string> action) => BuilderAction(() => {
                            Builder
                                .Append(CodeOfChaos.Ansi.AnsiCodes.Rgb{{section}}Color(CodeOfChaos.Ansi.AnsiColorStore.{{entry.Name}}))
                                .Append(action())
                                .AppendLine(CodeOfChaos.Ansi.AnsiCodes.ResetGraphicsModes);
                        });

                        public Ansi{{section}}Builder Append{{entry.Name}}Line(Action<Ansi{{section}}Builder> action) => BuilderAction(() => {
                            Builder.Append(CodeOfChaos.Ansi.AnsiCodes.Rgb{{section}}Color(CodeOfChaos.Ansi.AnsiColorStore.{{entry.Name}}));
                            action(this);
                            Builder.AppendLine(CodeOfChaos.Ansi.AnsiCodes.ResetGraphicsModes);
                        });
                        #endregion

                        """)
                    .AppendLine()
                )
                .AppendLine("}")
                .ToStringAndClear()
            );
        }
        #endregion
    }

    private static ColorEntry[] ParseColorFile(SourceProductionContext context, AdditionalText file) {
        try {
            string? fileContent = file.GetText(context.CancellationToken)?.ToString();
            if (fileContent is null || string.IsNullOrWhiteSpace(fileContent)) return [];

            // Use XmlSerializer to deserialize XML
            var serializer = new XmlSerializer(typeof(ColorEntryContainer));
            using var reader = new StringReader(fileContent);
            // Deserialize the XML into the container object
            var container = (ColorEntryContainer?)serializer.Deserialize(reader);

            // Map the Color attribute (comma-separated values) to the ColorCode int array
            return container?.Entries
                .Select(entry => entry.ToColorEntry())
                .ToArray() ?? [];
        }
        catch (InvalidOperationException ex) {
            // Report a diagnostic if XML parsing fails
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor(
                    "ASB01",
                    "Invalid XML Format",
                    $"Failed to parse the XML file: {file.Path}. Error: {ex.Message}",
                    "CodeGeneration",
                    DiagnosticSeverity.Warning,
                    true),
                Location.None));

            return [];
        }
        catch (FormatException ex) {
            // Handle errors when parsing color values
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor(
                    "ASB02",
                    "Invalid Color Formatting",
                    $"Error while parsing RGB values in file: {file.Path}. Error: {ex.Message}",
                    "CodeGeneration",
                    DiagnosticSeverity.Warning,
                    true),
                Location.None));

            return [];
        }
    }
}
