<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>

        <!-- Main package name -->
        <PackageId>CodeOfChaos.Ansi</PackageId>
        <Version>1.1.0</Version>
        <Authors>Anna Sas</Authors>
        <Description>A small library to use Fluent style-ish string builders to add color to your console output</Description>
        <PackageProjectUrl>https://github.com/code-of-chaos/cs-code_of_chaos-ansi/</PackageProjectUrl>
        <PackageTags>ansi input stringbuilder</PackageTags>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <IncludeSymbols>true</IncludeSymbols>
        <DebugType>embedded</DebugType>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>icon.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../../LICENSE" Pack="true" PackagePath="" Visible="false" />
        <None Include="../../README.md" Pack="true" PackagePath="" />
        <None Include="../../assets/icon.png" Pack="true" PackagePath="" Visible="false" />
    </ItemGroup>

    <ItemGroup>
        <!-- ProjectReference for the generator as an analyzer -->
        <ProjectReference Include="..\CodeOfChaos.Ansi.Generators\CodeOfChaos.Ansi.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup>
        <None Include="Assets\ASB.CssColors.xml" />
        <AdditionalFiles Include="Assets\ASB.CssColors.xml" />
    </ItemGroup>

</Project>
