<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>

        <!-- Main package name -->
        <PackageId>CodeOfChaos.Ansi</PackageId>
        <Version>1.0.0-preview.0</Version>
        <Authors>Anna Sas</Authors>
        <Description>A library to write Ansi Colored text as a stringbuilder</Description>
        <PackageProjectUrl>https://github.com/code-of-chaos/cs-code_of_chaos-ansi/</PackageProjectUrl>
        <PackageTags>ansi input stringbuilder</PackageTags>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <IncludeSymbols>true</IncludeSymbols>
        <DebugType>embedded</DebugType>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>icon.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../../LICENSE" Pack="true" PackagePath="" Visible="false"/>
        <None Include="../../README.md" Pack="true" PackagePath=""/>
        <None Include="../../assets/icon.png" Pack="true" PackagePath="" Visible="false"/>
    </ItemGroup>

    <ItemGroup>
        <!-- ProjectReference for the generator as an analyzer -->
        <ProjectReference Include="..\CodeOfChaos.Ansi.Generators\CodeOfChaos.Ansi.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>

        <!-- Ugly, but this is because of some weirdness with how analyzers are imported through a project reference -->
        <PackageReference Include="CodeOfChaos.GeneratorTools" Version="1.2.0" GeneratePathProperty="true" PrivateAssets="all"/>
        <Analyzer Include="$(PkgCodeOfChaos_GeneratorTools)\lib\netstandard2.0\*.dll"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="Assets\ASB.CssColors.xml"/>
        <AdditionalFiles Include="Assets\ASB.CssColors.xml"/>
    </ItemGroup>

</Project>
